# Generated by Django 5.2 on 2025-04-23 13:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('roll_no', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Roll number must follow format: 22d41a6256', regex='^\\d{2}d41a\\d{4}$')])),
                ('year', models.PositiveSmallIntegerField()),
                ('branch', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=15)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('role', models.CharField(choices=[('Leader', 'Leader'), ('Crew', 'Crew')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.CharField(editable=False, max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('no_of_teams', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('team_code', models.CharField(blank=True, max_length=10, null=True)),
                ('team_name', models.CharField(max_length=100, unique=True)),
                ('submission_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('team_leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_team', to='web.participant')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.topic')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.team'),
        ),
    ]
