# Generated by Django 5.2 on 2025-04-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('Leader', 'Leader'), ('Crew', 'Crew')], max_length=20, null=True),
        ),
    ]
