# Generated by Django 5.2 on 2025-04-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_participant_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_size',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
